### ISSUE TITLE
No preprocess/vctk.config and preprocess.sh file ?

### ISSUE THREAD

**Issue by Husnain08** [jjery2243542/voice_conversion#10]
Hi @jjery2243542 
According to new documentation, there is no preprocess/vctk.config file present and neither is the preprocess.sh file?
Am I missing something ?

**Comment by Husnain08** [comment]
And when running the preprocess.py file, we should provide a path for an h5py file which is also not present in the repo?
Is it somewhere and I am missing anything?

**Comment by jjery2243542** [comment]
Hi,
1. I have uploaded vctk.config and preprocess.sh.
2. h5py file is the path to store the extracted feature.

Thank you.
