### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Husnain08** [jjery2243542/voice_conversion#11]
When I run the make_dataset_vctk.py script, I get the following error. I am using the following file as the speaker-info.txt. The error message is also attached to this. 
Am I missing something?
[speaker-info.txt](https://github.com/jjery2243542/voice_conversion/files/3517126/speaker-info.txt)
![mistake](https://user-images.githubusercontent.com/38109416/63289040-967c5a80-c2d7-11e9-8899-ccf3d36c241a.PNG)

**Comment by jjery2243542** [comment]
No, the speaker-info.txt is provided by VCTK, not this list.

**Comment by Husnain08** [comment]
This solved my problem. Now I am using this file and it's also giving me a strange error. Can you please take a look?
[speaker-info.txt](https://github.com/jjery2243542/voice_conversion/files/3517283/speaker-info.txt)
![Uploading ms.PNG…]()

**Comment by Husnain08** [comment]
This solved my problem. Now I am using this file and it's also giving me a strange error. Can you please take a look?
[speaker-info.txt](https://github.com/jjery2243542/voice_conversion/files/3517285/speaker-info.txt)
![ms](https://user-images.githubusercontent.com/38109416/63292072-4d7bd480-c2de-11e9-893e-895a5122cebf.PNG)

**Comment by Husnain08** [comment]
@jjery2243542 I figured out the solution. In the preprocessing file, you used the following
speaker_id, utt_id = re.match(r'p(\d+)_(\d+)\.wav', (sub_filename)).groups()
However, re.match checks for a match only at the beginning of the string which is not the case. Just change this line to 
speaker_id, utt_id = re.search(r'p(\d+)_(\d+)\.wav', str(sub_filename)).groups()
And this problem is solved
