### ISSUE TITLE
Please provide the file or help me solve the issue?

### ISSUE THREAD

**Issue by Husnain08** [jjery2243542/voice_conversion#15]
Please provide the file which is referred in -index path**the path of sampled segment indexes (.json).**. 

or help me solve this issue when I get this error while running make_single_samples.py?
![1](https://user-images.githubusercontent.com/38109416/63358920-422fb400-c385-11e9-83d5-b998bd3b50a0.PNG)

**Comment by jjery2243542** [comment]
Hi,
the index file is the path to **write**.
And do you successfully make_dataset? I didn't have this error when I was running the code.

**Comment by Husnain08** [comment]
@jjery2243542  yes I successfully ran the make_dataset and it gave a .h5 as an output.
The problem is the make_samples file which is giving this error?
Can you please provide the json file you got after running that file ? What do you think is wrong with this error?

**Comment by Husnain08** [comment]
can you please help @jjery2243542

**Comment by jjery2243542** [comment]
Hi,
[used speaker file path], this argument is the file 225\n226\n227.... not the one provided by VCTK.
